FROM openjdk:8-jdk

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y \
    build-essential && \
    rm -rf /var/lib/apt/lists/*

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get install -y nodejs

WORKDIR /usr/src

CMD ["/bin/bash"]
