FROM hasli/ui-build-env:latest

ADD config /root/.jspm/

EXPOSE 8081

CMD chmod +x /usr/src/gradlew  \
	&& cd /usr/src/ \
	&& ./gradlew installEnvironment \
	&& ./gradlew clean build -x test \
    && cp /usr/src/web-site/build/libs/web-site*.jar /web-site.jar \
    && java -jar /web-site.jar
